version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Europe/Madrid"
    groups:
      gomod-minor-patch:
        applies-to: version-updates
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Europe/Madrid"
    groups:
      actions-all:
        applies-to: version-updates
        patterns:
          - "*"
