style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Ericson246/npu-optimize
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - docs
        - test
        - refactor
  commit_groups:
    title_maps:
      feat: Added
      fix: Fixed
      docs: Documentation
      test: Tests
      refactor: Refactored
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
